# Generated by Django 5.1.5 on 2025-02-07 20:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fixture",
            name="away_team_crest",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="fixture",
            name="home_team_crest",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
