# Generated by Django 5.1.5 on 2025-01-31 20:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leagues", "0002_league_users"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="league",
            name="users",
            field=models.ManyToManyField(
                related_name="leagues", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
