# Generated by Django 5.1.5 on 2025-02-01 00:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leagues", "0004_league_join_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="league",
            name="join_code",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
